name: cellstream-env
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # PyTorch and core scientific computing
  - pytorch=*=*cuda*
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8
  - torchvision
  - numpy<2
  - pandas
  - pyarrow
  - scipy
  - cupy
  
  - pytorch-scatter #pyg should pull correct build
  
  # Image analysis and GUI dependencies
  - napari
  - pyqt
  - rich
  - tifffile
  - zarr
  - matplotlib
  
  # Pip for packages not available or reliably maintained in conda channels
  - pip
  - pip:
      - nd2
      - ssqueezepy  # CWT backend
      - pystackreg  # Registration backend
      - git+https://github.com/coylelab/cellstream.git
      - git+https://github.com/coylelab/napari-cellstream.git
