[project]
name = "cellstream"
version = "0.1.1"
description = "Microscopy and single-cell signal processing analysis tools"
authors = [{ name = "Coyle Lab @ UW-Madison" }]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "tifffile",
    "nd2",
    "tqdm",
    "ssqueezepy",
    "zarr",
    "pyarrow"
]

[project.optional-dependencies]
registration = ["pystackreg"]
filters = []
profiling = ["psutil", "scipy"]
viz = ["napari"]
all = ["cellstream[registration,filters,profiling,viz]"]

[tool.setuptools.packages.find]
where = ["."]
include = ["cellstream*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

