import pytest
import os
import shutil
import zarr
import numpy as np
import torch

from cellstream.fft.process import process_zarr_store as process_fft_zarr
from cellstream.cwt.process import process_zarr_store as process_cwt_zarr
from cellstream.phase.process import process_zarr_store as process_phase_zarr

@pytest.fixture
def mock_crop_zarr(tmp_path):
    """Create a mock crop Zarr store with 2 cells."""
    store_path = str(tmp_path / "mock_crops.zarr")
    store = zarr.open(store_path, mode='w')
    cells = store.create_group('cells')
    
    # 2 fake cells
    for i in range(1, 3):
        cg = cells.create_group(f"cell_{i}")
        
        # Raw Timeseries (T, C, Y, X) -> 50 frames, 1 channel, 16x16
        data = np.random.randn(50, 1, 16, 16).astype('float32')
        cg.create_dataset('Channel_0', data=data)
        
        # Mask
        mask = np.ones((16, 16), dtype='float32')
        cg.create_dataset('mask', data=mask)
        
    return store_path

def test_full_zarr_pipeline(mock_crop_zarr):
    """
    Test that the FFT, CWT, and Phase batch processing scripts 
    can sequentially process a mock crop Zarr store.
    """
    # 1. FFT Processing
    # Should detect Channel_0, process it, and create fft/Channel_0/phase, etc.
    fft_processed = process_fft_zarr(
        mock_crop_zarr, 
        force=True, 
        fft_features_to_process=["full_amplitude", "phase"]
    )
    
    # 2. CWT Processing
    cwt_processed = process_cwt_zarr(
        mock_crop_zarr, 
        force=True, 
        min_scale=80, 
        max_scale=100, 
        num_filter_banks=1,
        channel_outputs={0: ["amp", "phase"]}
    )
    
    # 3. Phase Processing
    # Should detect the phase arrays generated by FFT and CWT
    phase_processed = process_phase_zarr(
        mock_crop_zarr,
        force=True,
        phase_features_to_process=["winding_number", "velocity"]
    )
    
    # Assertions
    store = zarr.open(mock_crop_zarr, mode='r')
    
    for i in range(1, 3):
        cell_group = store[f"cells/cell_{i}"]
        
        # Check FFT output
        assert "fft" in cell_group
        assert "Channel_0" in cell_group["fft"]
        assert "phase" in cell_group["fft"]["Channel_0"]
        assert cell_group["fft"]["Channel_0"]["phase"].shape == (26, 1, 16, 16)
        
        # Check CWT output
        assert "cwt" in cell_group
        assert "Channel_0" in cell_group["cwt"]
        assert "channel_0" in cell_group["cwt"]["Channel_0"] # nested channel_output key
        assert "phase" in cell_group["cwt"]["Channel_0"]["channel_0"]
        assert cell_group["cwt"]["Channel_0"]["channel_0"]["phase"].shape == (50, 1, 16, 16)
        
        # Check Phase output (velocity)
        assert "flow" in cell_group["fft"]["Channel_0"]
        assert "velocity" in cell_group["fft"]["Channel_0"]["flow"]
        assert cell_group["fft"]["Channel_0"]["flow"]["velocity"].shape == (26, 2, 16, 16)
